[[main]]
none = "none"

[[main]]
name = "CTF Writeups"
pageRef = "ctf"
identifier = "MF8pWZJQQR"
weight = 9999

[[main]]
name = "HTB Writeups"
pageRef = "htb"
identifier = "n0W2DB0V1F"
weight = 9999

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "sprNPzVRx4"
weight = 9999

[[footer]]
none = "none"
