[[main]]
none = "none"

[[main]]
name = "Writeups"
pre = "ghost"
pageRef = "writeups"
identifier = "4zpI1yOaOj"
weight = 1

[[main]]
name = "Tags"
pre = "hashnode"
pageRef = "tags"
identifier = "yehLyeqKMT"
weight = 2

[[footer]]
none = "none"
